### ISSUE TITLE
project folder structure is not correct

### ISSUE THREAD

**Issue by kefeimo** [VOLTTRON/copier-poetry-volttron-agent#33] opened 2022-04-21 03:04 UTC
project folder structure is not correct should not be nested or lack of outer wrap

**Comment by bonicim** [comment] 2022-04-22 16:07
Issue is duplicate of #32

**Closed as completed by bonicim** 2022-04-22 16:07 UTC

**Comment by kefeimo** [comment] 2022-04-24 18:31
Fixed by https://github.com/VOLTTRON/copier-poetry-volttron-agent/pull/39 (info for housekeeping).
